### ISSUE TITLE
Specify name for folder

### ISSUE THREAD

**Issue by pauldruziak** [zedtux/ror-refactor#1]
Can you add option to specify name of folder (instead app/interactors)?

**Comment by zedtux** [comment]
Thank you @paveldruzyak for this issue.

The package is for now compatible only with the [interactor gem](https://github.com/collectiveidea/interactor).
Are you asking to simply change the folder name, but using that gem, or are you asking for another library or PORO objects?

**Comment by pauldruziak** [comment]
We use PORO objects, so it will be cool to have support of custom templates of course. But at least ability to change folder name will be enough for now.

**Comment by zedtux** [comment]
Okay, I had anyway planed to implement PORO objects as well. So we need an option in order to select the kind of service refactoring we like to use (interactor or PORO for now).

**Comment by zedtux** [comment]
@paveldruzyak can you please post an example of a basic class you're creating with refactoring as a new service please?

**Comment by zedtux** [comment]
@paveldruzyak do you agree to use the path `app/services` in case of PORO or you really want the input text field where to put the folder name?

**Comment by zedtux** [comment]
@paveldruzyak I have implemented the following:
- Now you have an option in the package settings where you can choose the service extract template (PORO or Interactor)(PORO by default)
- When extracting as a new service some methods, the right template is used
- The PORO template is almost the same as the Interactor one, excepted that I have removed the `include Interactor` line AND the file path is `app/services`

Can you please tell me if this fits your need or if there is anything I should change?

**Comment by pauldruziak** [comment]
Here is example from our project:

``` ruby
# app/commands/events/create.rb

module Events
  class Create
    include Command

    def perform
      some_method if event.save
    end

    private

    def some_method
    end
  end
end
```

**Comment by zedtux** [comment]
Well now I see some issues with the PORO version:
1. You're including a `Command` class
2. You're using a `perform` method instead of `call`
3. You're using a folder `app/commands/...`

For all those points, I will look for a standard way of doing it. People not following the standard will have to fork the project and customise it for themselves.

I'll update this ticket when I'll found the standard way.

**Comment by pauldruziak** [comment]
Or maybe you can provide field in settings, where users can specify the folder name?
Because template is not so important for me right now, at least for now.
And maybe support for module? Like example: if user enter the name `events/create` it will create `Events::Create` inside `app/<folder>/events/create`.

**Comment by zedtux** [comment]
Okay, let's go this way if you agree:
1. Selecting the PORO option allows the user to fill in the services path setting with a folder name (covering your initial request)
2. The service name that the user fills in is the class name, not the path, so in case the user fill in with `Events::Create`, the module will create/use an `events` folder within the service directory and then create the file
3. A common setting to the template options PORO and Interactor allows the user to set a module name to always add when creating the service (but when this setting is empty, nothing will be added).

**Comment by zedtux** [comment]
I still need to write the tests for this but at least it should work. @paveldruzyak can you please give it a try from the **master** branch and let me know if it's working as expected?

**Comment by zedtux** [comment]
@paveldruzyak I just realise that I forgot the second point... I'll implement it but at least you can validate points 1 and 3.

**Comment by pauldruziak** [comment]
@zedtux 👍 yes, it works. Thanks

**Comment by zedtux** [comment]
@paveldruzyak I just pushed an update in order to convert `Namespace::ClassName` into `namespace/class_name.rb`.

Can you please give it a try and let me know? Then I will build a release.

**Comment by zedtux** [comment]
I just did a fix for the multiple namespaces case (I.e: `Namespace1::Namespace2::ClassName` is transformed to `namespace1/namespace2/class_name.rb`)

**Comment by zedtux** [comment]
@paveldruzyak any chance you test the last part soon? Or are the your emojis validating my dev? 😛

**Comment by pauldruziak** [comment]
@zedtux yes, they are. Great job 👍

**Comment by zedtux** [comment]
Okay, I'll then publish a new release :) Thank you @paveldruzyak

**Comment by zedtux** [comment]
The new release has been publish. You should get an update in Atom :)
